[shell]
program = "/usr/bin/zsh"

[window]
decorations = "None"
opacity = 1.0

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 0
y = 0

[font]
size = 12.0
builtin_box_drawing = false

[font.normal]
family = "Cascadia Code"
style = "Regular"

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.bold_italic]
family = "Cascadia Code"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = false
# indexed_colors = [
#     { index = 16, color = "#fab387" },
#     { index = 17, color = "#f5e0dc" },
# ]

[colors.cursor]
text = "{color0}"
cursor = "{color5}"

# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"

[colors.selection]
text = "{color0}"
background = "{color5}"

# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"

# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"

# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6acd8"

[colors.primary]
background = "{color0}"
foreground = "{color6}"
# dim_foreground = "#cdd6f4"
# bright_foreground = "#cdd6f4"

[colors.normal]
black = "{color0}"
red = "{color8}"
green = "{color11}"
yellow = "{color10}"
blue = "{color13}"
magenta = "{color14}"
cyan = "{color12}"
white = "{color6}"

# [colors.bright]
# black = "#928374"
# red = "#FB4934"
# green = "#B8BB26"
# yellow = "#FABD2F"
# blue = "#83A598"
# magenta = "#D3869B"
# cyan = "#8EC07C"
# white = "#EBDBB2"

# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

[selection]
save_to_clipboard = false
