swipe:
  4:
    left:
      command: 'xdotool key ctrl+shift+super+period'
    right:
      command: 'xdotool key ctrl+shift+super+comma'
    # up:
    #   command: 'xdotool key ctrl+shift+plus'
    # down:
    #   command: 'xdotool key ctrl+minus'
  3:
    left:
      command: 'xdotool key super+period'
    right:
      command: 'xdotool key super+comma'
pinch:
  in:
    command: 'xdotool key ctrl+minus'
  out:
    command: 'xdotool key ctrl+plus'

threshold:
  swipe: 0.5
  pinch: 0.2

interval:
  swipe: 0.7
  pinch: 0.4
