[mgr]
ratio = [1, 4, 3]
show_hidden = true
show_symlink = true
linemode = "mtime"

[opener]
metadata = [
    { run = '''exiftool %s1 | less''', block = true, desc = "Show EXIF", for = "unix" },
    { run = '''exiftool %s1 | less''', block = true, desc = "Show EXIF", for = "android" },
    { run = '''mediainfo %s1 | less''', block = true, desc = "Show media info", for = "unix" },
    { run = '''mediainfo %s1 | less''', block = true, desc = "Show media info", for = "android" },
]

[open]
append_rules = [
    { mime = "{audio,video}/*", use = ["open", "metadata"] },
]
