[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "None"
opacity = 1.0

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 10
y = 10

[font]
size = 12.0
builtin_box_drawing = false

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = false
# indexed_colors = [
#     { index = 16, color = "#fab387" },
#     { index = 17, color = "#f5e0dc" },
# ]

[colors.cursor]
text = "#282828"
cursor = "#d5c4a1"

# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"

[colors.selection]
text = "#282828"
background = "#d5c4a1"

# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"

# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"

# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6acd8"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
# dim_foreground = "#cdd6f4"
# bright_foreground = "#cdd6f4"

[colors.normal]
black = "#282828"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.bright]
black = "#928374"
red = "#FB4934"
green = "#B8BB26"
yellow = "#FABD2F"
blue = "#83A598"
magenta = "#D3869B"
cyan = "#8EC07C"
white = "#EBDBB2"

# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

[selection]
save_to_clipboard = false
